const labels = {
  NOT_MADE: 'No decision made',
  NOT_ESTABLISHED: 'Not established',
  NOT_EVALUATED: 'Requires human review',
  NOT_RUN: 'No model used',
  NOT_PERFORMED: 'Not submitted',
  NOT_PROVIDED: 'Not provided',
  REFERENCE_ONLY_NO_ACTION_AUTHORIZATION: 'Reference only · no action authorized',
  READY_FOR_LOCAL_REVIEW: 'Ready for human review',
  CASE_NOT_ACTIONABLE: 'Case is not actionable',
  MANUAL_REVIEW: 'Needs manual review',
  DUE_DATE_EXPIRED: 'Response window expired',
  ACTION_NOT_AVAILABLE: 'Required action is unavailable',
  NEEDS_INPUT: 'More information needed',
  OPEN: 'Response window open',
  EXPIRED: 'Response window expired',
  WAITING_FOR_SELLER_RESPONSE: 'Waiting for seller response',
  WAITING_FOR_BUYER_RESPONSE: 'Waiting for buyer response',
  UNDER_REVIEW: 'Under review',
  RESOLVED: 'Resolved',
  CLOSED: 'Closed',
  UNKNOWN: 'Needs review',
  INQUIRY: 'Inquiry',
  CHARGEBACK: 'Chargeback',
  PRE_ARBITRATION: 'Pre-arbitration',
  ARBITRATION: 'Arbitration',
  MERCHANDISE_OR_SERVICE_NOT_RECEIVED: 'Item or service not received',
  MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED: 'Item or service not as described',
  UNAUTHORISED: 'Unauthorized activity',
  CREDIT_NOT_PROCESSED: 'Credit not processed',
  DUPLICATE_TRANSACTION: 'Duplicate transaction',
  INCORRECT_AMOUNT: 'Incorrect amount',
  PAYMENT_BY_OTHER_MEANS: 'Paid by another method',
  CANCELED_RECURRING_BILLING: 'Canceled recurring billing',
  OTHER: 'Other evidence',
  REQUESTED_FROM_SELLER: 'Requested from seller',
  PROVIDE_EVIDENCE: 'Prepare evidence',
  PROOF_OF_FULFILLMENT: 'Proof of fulfillment',
  PROOF_OF_REFUND: 'Proof of refund',
  FULFILLMENT: 'Fulfillment record',
  CONTEXT_ONLY: 'Context only',
  UNMAPPED_EVIDENCE_TYPE: 'Evidence type needs review',
  PROVIDER_REQUEST_OUTSIDE_LOCAL_MATRIX: 'Provider request needs manual review',
  STRUCTURALLY_PRESENT: 'Required fields present',
  MANDATORY_EVIDENCE_MISSING: 'Required evidence missing',
  OPTIONAL_EVIDENCE_MISSING: 'Optional evidence missing',
  INCOMPLETE_POLICY_EVIDENCE: 'Policy evidence incomplete',
  STRUCTURE_COMPATIBLE: 'Structure check passed',
  INCOMPLETE_EVIDENCE: 'Evidence incomplete',
  REJECTED: 'Needs review',
  SUMMARY_COVERAGE_INCOMPLETE: 'Source coverage is incomplete',
  CURRENT_POLICY_APPLICABILITY_NOT_ESTABLISHED: 'Current policy applicability is not established',
  CURRENT_POLICY_NOT_ESTABLISHED: 'Current policy is not established',
  FUTURE_OBSERVATION: 'Source timestamp is after the comparison time',
  STALE_OBSERVATION: 'Source is outside the selected age limit',
  WITHIN_OBSERVATION_BUDGET: 'Source is within the selected age limit',
  DOCUMENT_UPDATE_DATE_MISSING: 'Document update date is missing',
  DOCUMENT_UPDATE_IN_FUTURE: 'Document update date is after the comparison time',
  UNKNOWN_EFFECTIVE_DATE: 'Effective date is not verified',
  EFFECTIVE_DATE_IN_FUTURE: 'Effective date is after the comparison time',
  API_REFERENCE_NOT_POLICY: 'API guidance does not establish policy applicability',
  GUIDANCE_NOT_APPLICABLE_POLICY: 'Guidance does not establish current policy applicability',
  HISTORICAL_CASE_NOT_APPLICABLE_POLICY: 'Historical case does not establish current policy applicability',
  PROCEDURE_NOT_APPLICABLE_POLICY: 'Procedural record does not establish current policy applicability',
  NO_OFFICIAL_POLICY_COVERAGE: 'No official policy source covers this theme',
  NO_REFERENCE_COVERAGE: 'No matching reference coverage',
  ACTION_CLAIM_FORBIDDEN: 'Action claims are outside this review',
  ASSURANCE_CLAIM_FORBIDDEN: 'Assurance claims are outside this review',
  CITATION_UNKNOWN: 'Citation is not recognized',
  CITATION_REGION_MISMATCH: 'Citation region does not match',
  CITATION_THEME_MISMATCH: 'Citation theme does not match',
  CLAIM_REFERENCE_TYPE_MISMATCH: 'Citation type does not support this claim',
  DOCUMENT_STATED: 'Document stated',
  MISSING: 'Date missing',
  NOT_VERIFIED: 'Not verified',
  NOT_STATED_IN_REVIEWED_DOCUMENT: 'Not stated in the reviewed document',
  NOT_APPLICABLE: 'Not applicable',
  AUTHENTIC_SANDBOX_RESPONSE: 'Live Sandbox response',
  SYNTHETIC_TEST_RESPONSE: 'Synthetic test run',
  OPERATOR_LIVE_RESPONSE: 'Live model response',
  LOCAL_RUNTIME_RESPONSE: 'Local model response',
  POST_RESPONSE_ONLY: 'Verified from the response',
  CONNECTED: 'Connected',
  DRAFT: 'Draft · not sent',
  FROZEN: 'Not submitted',
  connected: 'Connected',
  disconnected: 'Disconnected',
  not_configured: 'Not configured',
  error: 'Connection error',
  needs_review: 'Needs review',
  draft_ready: 'Draft ready',
  local_draft_reviewed: 'Local review recorded',
  INR: 'Item not received',
  delivered: 'Delivered',
  synthetic: 'Synthetic record',
  unsupported_reason: 'Unsupported case reason',
  AUTHORED_SYNTHETIC_SCENARIOS_NOT_REAL_CASES: 'Authored synthetic scenario',
  SYNTHETIC_PROVIDER_FIXTURE: 'Synthetic provider record',
  SYNTHETIC_BASELINE: 'Synthetic baseline',
  CALLER_SUPPLIED_UNVERIFIED: 'Unverified supplied baseline',
  official_api_reference: 'Official PayPal API reference',
  official_policy: 'Official PayPal US policy',
  official_api_schema: 'Official PayPal API schema',
  official_policy_guidance: 'Official PayPal policy guidance',
  public_case_decision: 'Public case record',
  public_court_order_copy: 'Official US court procedural record',
  any: 'All source stages',
  procedural_order: 'Procedural order · not final merits',
  not_applicable: 'Policy or API document · not a case decision',
  SETTLEMENT_APPROVAL_NOT_FINAL_MERITS: 'Settlement approval · not a final merits finding',
  ARBITRATION_COMPELLED_UNDERLYING_MERITS_NOT_DECIDED: 'Arbitration compelled · underlying merits not decided',
  saved_retrieved_at_exact_elapsed_time: 'Saved retrieval time compared with the evaluation time',
  policy_reference: 'Policy reference',
  current_policy: 'Current-policy claim',
  historical_case: 'Historical case',
  procedural_reference: 'Procedural reference',
  api_reference: 'API reference',
  guidance_reference: 'Policy guidance reference',
  financial_action: 'Financial action',
  assurance: 'Assurance claim',
  'payguard-bounded-advisory-v2': 'Fixed advisory contract',
  PAYLOAD_DIGEST_BOUND: 'Draft details locked for this review',
  SEPARATE_READBACK_TRUE: 'Verified by a separate status check',
  SEPARATE_READBACK_FALSE: 'Verified from the creation response only',
  EXTERNAL_ACTION_FALSE: 'No external action authorized',
  DEMO_OPERATOR_UNAUTHENTICATED: 'Demo operator · identity not authenticated',
  SESSION_MEMORY_ONLY: 'Stored in this session',
};

export const OPERATOR_LABELS = Object.freeze(labels);

export function operatorLabel(value, fallback = 'Needs review') {
  if (typeof value !== 'string' || value.length === 0) return fallback;
  return Object.hasOwn(OPERATOR_LABELS, value) ? OPERATOR_LABELS[value] : fallback;
}

export function operatorLabels(values, fallback = 'Needs review') {
  if (!Array.isArray(values) || values.length === 0) return [];
  return values.map((value) => operatorLabel(value, fallback));
}

export function sandboxReadbackLabel(separateReadback) {
  return operatorLabel(separateReadback === true ? 'SEPARATE_READBACK_TRUE' : 'SEPARATE_READBACK_FALSE');
}
